import sys, numpy as np
import wormneuroatlas as wa

'''
The neuropeptidergic connectome generated by make_peptidergic_connectome.py
is a relatively big file. This script allows you extract the peptide/GPCR
combinations for selected neuron pairs. You can enter those pairs in a file in
which each line is, e.g.,

AVAL -> RMMDR

and pass the path to the file in the command with which you run this script,
e.g.

```python pep_connectome_extract_combos.py path/to/file.txt```

The script will produce a easily readable text file in the same folder as the 
input file.
'''

watlas = wa.NeuroAtlas()

# Allow to pass a file containing the pairs for which to save the combo of
# neuropeptide and GPCR.
extr_combo_for_fname = sys.argv[1]

ma_esconn = watlas.get_monoaminergic_connectome()

# Read in the requested pairs from the file and store the combo entries for 
# that pair.
f_extr_for = open(extr_combo_for_fname,"r")
f_extr = open(extr_combo_for_fname.split(".")[0]+"_pepgpcr_combos.txt","w")
combos = np.load("pep_connectome_pep_gpcr_combo.npy",allow_pickle=True)

for l in f_extr_for.readlines():
    neu_ids = l.rstrip().split("->")[::-1]
    pair = watlas.ids_to_ais(neu_ids)
    f_extr.write(l.rstrip()+"\n")
    for combo in combos[pair[0],pair[1]]:
        gp = combo.split("\t")[1]
        gp_name = watlas.pepgpcr.get_gpcr_name_from_seq_id(gp)
        gp_name = watlas.pepgpcr.trim_isoforms(gp_name)
        combo = combo.split("\t")[0]+"\t"+gp_name
        f_extr.write("\t"+combo+"\n")
    
    if ma_esconn[pair[0],pair[1]]:
        f_extr.write("\tand monoamines\n")
    
    if len(combos[pair[0],pair[1]])==0 and not ma_esconn[pair[0],pair[1]]:
        f_extr.write("\tNo direct extrasynaptic connection found. However, this does not exclude indirect connections that go through other neurons.\n")
    
f_extr_for.close()
f_extr.close()
